require("highbits.plugins")
require("highbits.options")
require("highbits.keymap")
require("highbits.color")
require("highbits.toggleterm")
require("highbits.lsp")
require("highbits.completion")
require("highbits.lualine")
